### ISSUE TITLE
Race condition in Android web server

### ISSUE THREAD

**Issue by JStumpp** [ionic-team/capacitor#153]
We try to build a capacitor app with stencil and vanilla javascript. In an android emulator it works (with Android Webview v58). But on a real device with latest Version 64 it does not work because of the following error in chrome remote debugger:
```Failed` to load module script: The server responded with a non-JavaScript MIME type of "". Strict MIME type checking is enforced for module scripts per HTML spec.```

This issue is already discussed here: https://stackoverflow.com/questions/48113359/es6-modules-imports-in-apache-cordova-hybrid-app-throw-mime-type-error

Any idea how to solve this?

**Comment by jcesarmobile** [comment]
Could you provide a sample project?

**Comment by JStumpp** [comment]
Sure, I just used the Stencil App Starter and added Capacitor. Here you find the example:
https://github.com/JStumpp/stencil-capacitor
Just run the android app. Don't be fooled by the prerendering, the app starts, but the JS is not loaded.
Android logcat also shows: `02-19 12:26:48.596 25765-25765/com.getcapacitor.app I/chromium: [INFO:CONSOLE(0)] "Failed to load module script: The server responded with a non-JavaScript MIME type of "". Strict MIME type checking is enforced for module scripts per HTML spec.", source: https://58b69576-5bc8-41b3-a368-b6fb2885dd4ccapacitorapp.net/build/app/cufq1558.js (0)
`

**Comment by JStumpp** [comment]
Seems to be a stencil issue: https://github.com/ionic-team/stencil/issues/517

**Comment by jcesarmobile** [comment]
That issue looks like some webview incompatibility.
But since Capacitor serves from http and not file, we can probably fix it anyway, so reopening.

**Comment by JStumpp** [comment]
Oh, true. It should be handeled here: https://github.com/ionic-team/capacitor/blob/master/android/capacitor/src/main/java/com/getcapacitor/WebViewLocalServer.java#L365
Any idea why it is not "application/javascript"?

**Comment by mlynch** [comment]
I'm noticing this even with the patch, I wonder if it's a race condition? Occasionally the mimetype will come back for those .js files as an icon

**Comment by janpio** [comment]
I could recreate the `mimetype=icon` problem by building the Android project while I have a `native-bridge.js` and `cordova.js` file (copied over from `/core`) but no `cordova_plugins.js` and `public/plugins` folder.

Logcat:
```
03-06 17:31:07.349 3436-3436/com.getcapacitor.app E/Capacitor: Unable to read file at path public/plugins
03-06 17:31:07.349 3436-3436/com.getcapacitor.app E/Capacitor: Unable to read public/cordova_plugins.js file, Cordova plugins will not work
```

Devtools screenshot:
![image](https://user-images.githubusercontent.com/183673/37044664-586647c6-2164-11e8-81ff-338a9fc371a5.png)

Meanwhile error modal displaying with no error:
![image](https://user-images.githubusercontent.com/183673/37044727-8607ab98-2164-11e8-9d4c-655faf8b45b6.png)

**Comment by JStumpp** [comment]
Looks like a multithreading-problem. Just did some debugging and two threads are calling the handler at the same time which causes really ugly side effects like the wrong mime type.

**Comment by mlynch** [comment]
K marking this as high priority to fix by next release

**Comment by mlynch** [comment]
Fixed!

**Comment by cleversolutions** [comment]
I'm still having this issue with alpha.35. I nuked my android folder today and recreated it. Webpack .js chunks are getting random mime types.
Below is the output of npx cap doctor.
```
$ npx cap doctor
npx: installed 1 in 1.636s
Path must be a string. Received undefined
C:\Users\evanm\dev\northBayEnforcer\node_modules\@capacitor\cli\bin\capacitor
   Capacitor Doctor
Dependencies:
  @capacitor/cli: 1.0.0-alpha.35
  @capacitor/core: 1.0.0-alpha.35
  @capacitor/android: 1.0.0-alpha.35
  @capacitor/ios: 1.0.0-alpha.35
  Capacitor Android: not installed
[success] Android looking great! �
```
I'm not sure if Capacitor Android: not installed is a problem..

**Comment by cleversolutions** [comment]
I think my error may be the result of a plugin I'm trying to develop and include in this project. If I run the app without the plugin, the mime types are fine. I'll try recreating the plugin with a fresh copy of alpha.35. I started it a few weeks ago so maybe it's introducing some problems since it's based on an older version of cap.

**Comment by mlynch** [comment]
Interesting. If you're able to share the plugin code (publicly or privately), I'd love to take a look. It's possible that a transitive dependency is overriding it.

However, given that multi-threading is involved here, it could be a race condition that is show up sometimes, so let's not count that out just yet.

**Comment by jcesarmobile** [comment]
Is it a Capacitor plugin?
Can you check the plugin's build.gradle?
It should contain `implementation 'ionic-team:capacitor-android:1+'`.
If it has `implementation 'ionic-team:capacitor-android:0.0.+'` it will get an older Capacitor version with the bug present, just replace with the one I mentioned

**Comment by cleversolutions** [comment]
@jcesarmobile that's exactly it. It's referencing 0.0.+
For reference the project source is hosted at https://github.com/cleversolutions/zebraCapacitor but what is checked in is a bit stale and not likely working. I nuked all the project files minutes ago and am recreating it from a generation with the cli. Once done, I'll add the updated plugin back to my project and retest.

**Comment by mlynch** [comment]
Sweet, well glad we figured that one out. @jcesarmobile any idea why that dependency would override the main one?

@cleversolutions awesome on the plugin. Any feedback on the plugin development process so far? We need to document it better, that's on the list

**Comment by jcesarmobile** [comment]
Let's wait until he tests, because maybe it's not fixed.

It should really use the app one as the plugin one is there just to make the plugin module build, and the app dependencies should take precedence over the modules dependencies, but gradle...

**Comment by cleversolutions** [comment]
After some brief testing it seems all the mime types are coming in correctly now. I guess we can blame my old plugin and gradle. Oh gradle.

@mlynch you already know the biggest problem: documentation. I built my plugin first as custom native code in a separate ionic project, that was easy (and well documented). I wanted to spin it into an npm package... that has been much more difficult. 

I'm not sure if this comes down to not knowing any better (again the documentation thing), but to use my plugin I still have to register it in the project which is using it. I think it totally fine to expect to register a plugin if your doing custom code, but I think people who npm install published packages would expect not to have to update their MainActivity.java. But now I'm getting way off topic.

Since I'm already getting off topic... I'm migrating one of our enterprise apps from Android native to Ionic because Ionic is just generally awesome. We can build apps far more efficiently with Ionic, those apps support both iOS and Android, Ionic is clean consistent and easy to understand and it has high developer happiness.
