### ISSUE TITLE
Beta 25 breaks ionic/pwa-elements camera modal

### ISSUE THREAD

**Issue by iaguilera14** [ionic-team/capacitor#1535]
Description of the problem:
It seems capacitor beta.25 breaks the camera plugin using ionic/pwa-elements with an ionic/angular project. When I update to beta 25 I receive the following error:
`TypeError: cameraModal.present is not a function error. `

If i revert to beta.24 it works again as expected.

Affected platform
- [ ] Android
- [ ] iOS
- [ ] electron
- [ X ] web

OS of the development machine
- [ ] Windows
- [ X ] macOS
- [ ] linux

Other information:
I am using the implementation described below. 
https://stenciljs.com/docs/angular/

Capacitor version:
Beta 25
node version:
v10.15.3
npm version:
6.9.0

Steps to reproduce:
Install Camera plugin on ionic/angular 4.4.0 project.
Integrate ionic/pwa-elements.
Call the Camera.getPhoto() function.
Get error.
`TypeError: cameraModal.present is not a function error. `

Downgrade to beta.24 and it all works.

**Comment by jcesarmobile** [comment]
did you update PWA elements too? there has been a 1.1.0 release

**Comment by iaguilera14** [comment]
@jcesarmobile I am running PWA elements 1.2.0 actually.

**Comment by mlynch** [comment]
Are you using the `import` method or are you including PWA Elements using the script tag approach?

**Comment by iaguilera14** [comment]
I am using the import method described in the stencil docs. Works perfectly on beta 24. These are the methods I am using to be more specific. 

https://stenciljs.com/docs/angular/

https://stackoverflow.com/questions/54589782/how-to-include-ionic-pwa-elements-in-an-ionic4-angular-build

**Comment by mlynch** [comment]
Okay checking internally to see if we've got our package configured incorrectly, supposedly that should work without all that complexity described in there.

In the meantime the script tag include should work

**Comment by iaguilera14** [comment]
@mlynch thanks for the advice. My only issue with the script tag is offline loading. Unless I am missing something there.

**Comment by coffeymatt** [comment]
I can reproduce the same issue.

**Comment by simonhaenisch** [comment]
It should work now with the current versions (at least it does for our app).

**Comment by iaguilera14** [comment]
This still doesn't work using the latest release and using the angular import method.

**Comment by iaguilera14** [comment]
I would also like to know what @coffeymatt asked.

**Comment by jcesarmobile** [comment]
Did you follow the instructions from the stack overflow answer?
If so, make sure you use the official docs, this should work
https://capacitor.ionicframework.com/docs/pwa-elements

**Comment by iaguilera14** [comment]
@jcesarmobile It does work now. My mistake. I hadn't updated to latest pwa-elements. Seems the animation of the camera modal is gone for some reason. But this isn't the place to log that. Thanks!

**Comment by mlynch** [comment]
The animation thing is temporary and will be coming back

**Comment by coffeymatt** [comment]
@jcesarmobile @mlynch 

I've updated to the latest versions of everything as of today:

Capacitor 1.0.0
Pwa elements 1.2.7
@ionic/angular: 4.4.2

In my angular/ionic app, just having the import as per the instructions (https://capacitor.ionicframework.com/docs/pwa-elements) doesn't work. E.g. if my main.ts is this:


```
import { enableProdMode } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { AppModule } from './app/app.module';
import { environment } from './environments/environment';

**import '@ionic/pwa-elements';**

if (environment.production) {
  enableProdMode();
}

platformBrowserDynamic().bootstrapModule(AppModule)
  .catch(err => console.log(err));
```

I just get the 'TypeError: cameraModal.present is not a function error'.


What I need to do instead is:

```
import { enableProdMode } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { AppModule } from './app/app.module';
import { environment } from './environments/environment';

**import { defineCustomElements } from '@ionic/pwa-elements/loader';**

if (environment.production) {
  enableProdMode();
}

platformBrowserDynamic().bootstrapModule(AppModule)
  .catch(err => console.log(err));

**defineCustomElements(window);**
```

Please correct my understanding if this is wrong, but surely using a script tag is no good for a PWA if it needs to work offline? I'm thinking stuff needs to be bundled into the build and in the manifest no?

If the above is the way to do this in an angular context, this needs to be reflected in your documentation, this as it is is confusing to me because of the above: https://capacitor.ionicframework.com/docs/pwa-elements/

**Comment by jcesarmobile** [comment]
Looks like you have the docs cached. The angular instructions in that link are

Angular

main.ts:

 ```
import { enableProdMode } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { AppModule } from './app/app.module';
import { environment } from './environments/environment';

import { defineCustomElements } from '@ionic/pwa-elements/loader';

if (environment.production) {
  enableProdMode();
}

platformBrowserDynamic().bootstrapModule(AppModule)
  .catch(err =&gt; console.log(err));

// Call the element loader after the platform has been bootstrapped
defineCustomElements(window);
```

**Comment by coffeymatt** [comment]
Thanks @jcesarmobile, you're quite right, I'm seeing cache. Those instructions looks good.
