### ISSUE TITLE
bug: cordova-plugin-background-geolocation causes build failure

### ISSUE THREAD

**Issue by keo9ren** [ionic-team/capacitor#2529]
# Bug Report

## Capacitor Version
Capacitor Doctor

Latest Dependencies:

@capacitor/cli: 1.5.0

@capacitor/core: 1.5.0

@capacitor/android: 1.5.0

@capacitor/ios: 1.5.0

Installed Dependencies:

@capacitor/ios not installed

@capacitor/cli 1.5.0

@capacitor/android 1.5.0

@capacitor/core 1.5.0

## Affected Platform(s)

- [x] Android
- [ ] iOS
- [ ] Electron
- [ ] Web

## Current Behavior
App doesn't compile.

## Expected Behavior
App compiles.

## Reproduction Steps
add cordova-plugin-background-geolocation to your project

## Other Technical Details
Android Logcat:
Path\android\capacitor-cordova-android-plugins\build\intermediates\library_manifest\debug\AndroidManifest.xml:70:9-74:39: AAPT: error: resource string/mauron85_bgloc_content_authority (aka appid:string/mauron85_bgloc_content_authority) not found.

**Comment by jcesarmobile** [comment]
What's the exact plugin id you are using? `I can't reproduce with `cordova-plugin-background-geolocation`, which makes sense because it's not the mauron85 one.
can you provide a sample app?

**Comment by jcesarmobile** [comment]
Closing as there was no response.

Please, when reporting cordova plugin incompatibility issues, provide the npm package name or github repository.

**Comment by keo9ren** [comment]
Sorry for the late reply, I was on holiday last week.

Here is the sample repo:
https://github.com/keo9ren/cap-mauron-geolocation

It's just an stencil app with added capacitor. If you remove the geolocatoin plugin the apps compiles fine. With the plugin I've got an compiler error. 

There's also an unanswered ticket filled on the geolocation repo.
https://github.com/mauron85/cordova-plugin-background-geolocation/issues/676

Really appreciate your work and hope that we can move to capacitor, at my company, soon.

Best Regards,

keo9ren

**Comment by jcesarmobile** [comment]
The plugin relies on 3 strings that are automatically added for Cordova, but not for Capacitor.

Just add this to your `strings.xml` file:
```
<string name="mauron85_bgloc_account_name">@string/app_name</string>
<string name="mauron85_bgloc_account_type">$PACKAGE_NAME.account</string>
<string name="mauron85_bgloc_content_authority">$PACKAGE_NAME</string>
```

**Comment by keo9ren** [comment]
Awesome, it works. Thanks a lot.

**Comment by KarthikEaswaramoorthi** [comment]
Where I can find strings.xml in ionic project? If I add those in android studio after build the project it automatically resets.

**Comment by cwoolum** [comment]
`android\app\src\main\res\values\strings.xml`

**Comment by ahrherrera** [comment]
I am having a similar issue, I fixed the mauron85_bgloc_content_authority link but there are other resources failing

Android resource linking failed
android\capacitor-cordova-android-plugins\build\intermediates\library_manifest\debug\AndroidManifest.xml:42:13-44:55: AAPT: error: resource xml/syncadapter (aka appid:xml/syncadapter) not found.
    
android\capacitor-cordova-android-plugins\build\intermediates\library_manifest\debug\AndroidManifest.xml:51:13-53:57: AAPT: error: resource xml/authenticator (aka appid:xml/authenticator) not found.

**Comment by andrewl94** [comment]
Do I have to do any command to capacitor to read again the strings.xml? I'm still getting error even after including the viariables.

**Comment by jgauna** [comment]
Same here

**Comment by JesucristoEsteban** [comment]
@jcesarmobile It works great, thanks!

**Comment by jongbonga** [comment]
The stings addition solved my `mauron85_bgloc_content_authority` problem but I'm getting ```
error: package android.support.annotation does not exist
import android.support.annotation.VisibleForTesting;
```
                                 ^

**Comment by tobika** [comment]
@jongbonga this should fix your problem: https://github.com/mauron85/cordova-plugin-background-geolocation/issues/693#issuecomment-716112654

**Comment by jongbonga** [comment]
> @jongbonga this should fix your problem: [mauron85/cordova-plugin-background-geolocation#693 (comment)](https://github.com/mauron85/cordova-plugin-background-geolocation/issues/693#issuecomment-716112654)

I just replied to the other issue. I'm still getting 
```
error: cannot find symbol
import androidx.core.content.LocalBroadcastManager;
```
                            ^
