### ISSUE TITLE
cordova-plugin-websocket-server does not work.

### ISSUE THREAD

**Issue by bcjat** [ionic-team/capacitor#2930]
Steps of installation.
1. `ionic integrations enable capacitor`
2. `npm i cordova-plugin-websocket-server --save`
3. `npm i @ionic-native/web-socket-server`
4. `ionic build`
5. `ionic cap sync`
6. `ionic cap add android`
7. `ionic cap sync` 

[Code in home.page.ts]

`import { Component } from '@angular/core';
import { WebSocketServer } from "@ionic-native/web-socket-server/ngx";

@Component({
  selector: 'app-home',
  templateUrl: 'home.page.html',
  styleUrls: ['home.page.scss'],
})
export class HomePage {
  log:any = '';
  constructor(private webserver:WebSocketServer ) {
  }

  initServer(){
    
     this.webserver.start( 8888, {}).subscribe({
      next: server => console.log(`Listening on ${server.addr}:${server.port}`),
      error:error=>{
        this.appendLog('error occured: '+error);
      }
    })
    
    this.webserver.watchOpen().subscribe({
      next: data=>{
      console.log(data);
      },
      error: error => console.log(error)
    })
  }
}`

[added `WebSocketServer` class in `provider` array of `home.module.ts` ]

after ran `ionic cap open android`
 installed app and this is console output error

Listning on undefined:undefined

TypeError: Cannot read property 'plugins' of undefined
    at Observable._subscribe (index.js:14)
    at Observable._trySubscribe (Observable.js:42)
    at Observable.subscribe (Observable.js:28)
    at HomePage.initServer (home.page.ts:24)
    at Object.eval [as handleEvent] (HomePage.html:21)
    at handleEvent (core.js:43993)
    at callWithDebugContext (core.js:45632)
    at Object.debugHandleEvent [as handleEvent] (core.js:45247)
    at dispatchEvent (core.js:29804)
    at core.js:42925

when tried to use without `@ionic/native` wrapper using `(<any>window).plugins` and `(<any>)window.cordova.plugins` again same error that plugins and cordova undefined respectively.

version output
`D:\workspace\dice-lan>ionic --version
5.4.2`

`D:\workspace\dice-lan>ng -- version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.3.26
Node: 12.16.1
OS: win32 x64
Angular: 8.2.14
... common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.26
@angular-devkit/build-angular     0.803.26
@angular-devkit/build-optimizer   0.803.26
@angular-devkit/build-webpack     0.803.26
@angular-devkit/core              8.3.26
@angular-devkit/schematics        8.3.26
@angular/cli                      8.3.26
@ngtools/webpack                  8.3.26
@schematics/angular               8.3.26
@schematics/update                0.803.26
rxjs                              6.5.5
typescript                        3.4.5
webpack                           4.39.2`

**Comment by jcesarmobile** [comment]
can you provide a sample app?

**Comment by bcjat** [comment]
Yes this is repository link

https://github.com/bcjat/local-web-socket.git

**Comment by jcesarmobile** [comment]
I can't reproduce in your sample app.
I get
```
TypeError: window.cordova.plugins.wsserver[fnName] is not a function
    at Observable._subscribe (home-home-module-es2015.js:30)
    at Observable._trySubscribe (vendor-es2015.js:109405)
    at Observable.subscribe (vendor-es2015.js:109391)
    at HomePage.initServer (home-home-module-es2015.js:216)
    at Object.eval [as handleEvent] (ng:///HomePageModule/HomePage.ngfactory.js:46)
    at handleEvent (vendor-es2015.js:74622)
    at callWithDebugContext (vendor-es2015.js:76241)
    at Object.debugHandleEvent [as handleEvent] (vendor-es2015.js:75876)
    at dispatchEvent (vendor-es2015.js:61709)
    at vendor-es2015.js:73554
home-home-module-es2015.js:211 Listening on undefined:undefined
```
but that looks like a problem with the types, not with capacitor. If I use the regular javascript access it works, example:

var wsserver = cordova.plugins.wsserver;
wsserver.start(8888, {
    // WebSocket Server handlers
    'onFailure' :  function(addr, port, reason) {
        console.log('Stopped listening on %s:%d. Reason: %s', addr, port, reason);
    },
    // WebSocket Connection handlers
    'onOpen' : function(conn) {
        /* conn: {
         'uuid' : '8e176b14-a1af-70a7-3e3d-8b341977a16e',
         'remoteAddr' : '192.168.1.10',
         'httpFields' : {...},
         'resource' : '/?param1=value1&param2=value2'
         } */
        console.log('A user connected from %s', conn.remoteAddr);
    },
    'onMessage' : function(conn, msg) {
        console.log(conn, msg); // msg can be a String (text message) or ArrayBuffer (binary message)
    },
    'onClose' : function(conn, code, reason, wasClean) {
        console.log('A user disconnected from %s', conn.remoteAddr);
    },
    // Other options
    'origins' : [ 'file://' ], // validates the 'Origin' HTTP Header.
    'protocols' : [ 'my-protocol-v1', 'my-protocol-v2' ], // validates the 'Sec-WebSocket-Protocol' HTTP Header.
    'tcpNoDelay' : true // disables Nagle's algorithm.
}, function onStart(addr, port) {
    console.log('Listening on %s:%d', addr, port);
}, function onDidNotStart(reason) {
    console.log('Did not start. Reason: %s', reason);
});
```
I get

> Listening on :::8888

**Comment by bcjat** [comment]
But sir when using ionic with capacitor how to reference cordova? As per joshua morony's book there will be `window.plugins` object exposed but its not available in this case.

**Comment by jcesarmobile** [comment]
no idea about what that book says, but the cordova plugins are in the same place as if it was a cordova app, so it depends on the plugin, in this case, the plugin is in `cordova.plugins.wsserver`

**Comment by bcjat** [comment]
ok thank you so much sir there may be problem in Types I will prefer to go with plain Javascript.

**Comment by ritxweb** [comment]
Same problem here. Is there any way to run this plugin with capacitor? can you provide an example or an example of the javascript solution?

**Comment by bcjat** [comment]
It is solved, use plain javascript without Types. 
declare this variable beneath last import statement

`declare var cordova:any`

and then in constructor in platform ready method use like
```
this.platform.ready().then(() => {
   var wsserver = cordova.plugins.wsserver;
   wsserver.start(
      8888,
      {
        // WebSocket Server handlers
        onFailure: function (addr, port, reason) {
          console.log(
            "Stopped listening on %s:%d. Reason: %s",
            addr,
            port,
            reason
          );
        },
        // WebSocket Connection handlers
        onOpen: (conn) => {
          this.openWatch(conn);
        },
        onMessage: function (conn, msg) {
          console.log(conn, msg); // msg can be a String (text message) or ArrayBuffer (binary message)
        },
        onClose: function (conn, code, reason, wasClean) {
          console.log("A user disconnected from %s", conn.remoteAddr);
        },
        // Other options
        //origins: ["file://"], // validates the 'Origin' HTTP Header.
        //protocols: ["my-protocol-v1", "my-protocol-v2"], // validates the 'Sec-WebSocket-Protocol' HTTP Header.
        tcpNoDelay: true, // disables Nagle's algorithm.
      },
      function onStart(addr, port) {
        console.log("Listening on %s:%d", addr, port);
      },
      function onDidNotStart(reason) {
        console.log("Did not start. Reason: %s", reason);
      }
    );
});
```

**Comment by ritxweb** [comment]
Thanks!! this "declare var cordova:any"  was what I was missing. Anyway capacitor still not work with this cordova plugin.

**Comment by nihalak** [comment]
Hi got the same error , how to use pure js with websocker server in ionic-react app ?

**Comment by nihalak** [comment]
I solved this ,
Change declare var cordava : any;, in nodemodules/@types/corodova/index

**Comment by julientype** [comment]
it simply a bad call back service with java
i get undefined ... error on call back .... 
needs to be like this
start
exec(<successFunction>, <failFunction>, <service>, <action>, [<args>]);
he needs to feed args correctly..... as one json object to start server
respond 
exec(<successFunction>, <failFunction>, <service>, <action>, [<args>]);
error
exec(<successFunction>, <failFunction>, <service>, <action>, [<args>]);

and run different call backs in java to cordova
he has it all as one call back ..... 
result.action  <---- silly call back switch  just send the  result object to us... your done

**Comment by robson-danilo** [comment]
Alguém conseguiu resolver isso? a saída continua sendo Listening on :::8888
