### ISSUE TITLE
only vibrate() is working from haptics-Plugin (android)

### ISSUE THREAD

**Issue by WhippyM** [ionic-team/capacitor#3406]
Hi there,

I try to use the [haptics plugin](https://capacitorjs.com/docs/apis/haptics), but for example the device (android 8, Samsung Galaxy A3) only shows reaction on vibrate().
Is there a known bug already? I need more than one signal type to use this in our project.

- vibrate
working 😄 
- impact (all types)
no reaction
- selectionChanged
no reaction
- selectionStart(/End)
no reaction
- notification (all types)
```
Error: not implemented Error: not implemented
        at Object.fromNative (capacitor-runtime.js:230:14)
        at <anonymous>:1:18
```
Is there a Roadmap when this functions will work? 🎯

**Comment by dwieeb** [comment]
This is being fixed in Capacitor 3 with the new Haptics plugin: https://github.com/ionic-team/capacitor-plugins/pull/5

**Comment by merganon** [comment]
Still not working on Capacitor 3. Only `Haptics.vibrate();` works. Am I missing something?

```
   Capacitor Doctor   

Latest Dependencies:

  @capacitor/cli: 3.2.3
  @capacitor/core: 3.2.3
  @capacitor/android: 3.2.3
  @capacitor/ios: 3.2.3

Installed Dependencies:

  @capacitor/cli: 3.2.2
  @capacitor/android: 3.2.2
  @capacitor/ios: 3.2.2
  @capacitor/core: 3.2.2
```

@imhoffd @WhippyM

**Comment by merganon** [comment]
Every function mentioned in https://capacitorjs.com/docs/apis/haptics works for Android
However on iOS only `Haptics.vibrate();` is working

Is this intentional? If yes, we should update the documentation
