### ISSUE TITLE
bug: CLI isn't able to find Android 11(30) emulator targets

### ISSUE THREAD

**Issue by phiberber** [ionic-team/capacitor#4571]
### Capacitor Version
```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 2.4.7
  @capacitor/core: 2.4.7
  @capacitor/android: 2.4.7
  @capacitor/ios: 2.4.7

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 3.0.0-rc.3
  @capacitor/core: 3.0.0-rc.3
  @capacitor/android: 3.0.0-rc.3

[success] Android looking great! 👌
```

### Platform(s)
Android

### Current Behavior
When using the run command in the CapacitorJS v3.0 CLI to run the Android Emulator it doesn't do anything, by searching a little you find out that the real problem is that it can't find any target to emulate.

### Expected Behavior
It should prompt the user asking which target he wants to emulate on, listing all the possible AVD targets.

### Code Reproduction
https://github.com/phiberber/capacitorjs-target-issue

### Other Technical Details

Operational System: MacOS

Installed Emulator SDK: Android 11.0 (R) - Api Level 30
Android SDK Tools Version: Android SDK Build-Tools 31-rc3
Android Emulator Version: 30.6.5
 
`npm --version` output:
6.14.12
`node --version` output:
v14.16.1
`pod --version` output (iOS issues only):

### Additional Context

Here's the result of the command `npx cap run android --target 0`:

```
✔ Copying web assets from dist to android/app/src/main/assets/public in 60.63ms
✔ Creating capacitor.config.json in android/app/src/main/assets in 2.30ms 
✔ copy android in 109.77ms 
✔ Updating Android plugins in 7.11ms 
✔ update android in 97.62ms
[error] Invalid target ID: 0.
        Valid targets are:
```

**Comment by pavi2410** [comment]
It seems like Android SDK 30 isn't supported at the moment.

>  **native-run:android:utils:avd:getDefaultAVDSchematic Issue with API 30: Unsupported API level: 30 +0ms**

```
d:\GitHub\wisebrains\hellonotes>npx native-run android --list --verbose
  native-run:android:utils:sdk:resolveSDKRoot Looking for $ANDROID_HOME +0ms
  native-run:android:utils:sdk:resolveSDKRoot Using $ANDROID_HOME at D:\AndroidSDK +5ms
  native-run:android:utils:sdk:resolveEmulatorHome Looking for $ANDROID_EMULATOR_HOME +0ms
  native-run:android:utils:sdk:resolveEmulatorHome Looking at $HOME/.android +0ms
  native-run:android:utils:sdk:resolveEmulatorHome Using $HOME/.android/ at C:\Users\Pavitra\.android +0ms
  native-run:android:utils:sdk:resolveAVDHome Looking for $ANDROID_AVD_HOME +0ms
  native-run:android:utils:sdk:resolveAVDHome Looking at $HOME/.android/avd +0ms
  native-run:android:utils:sdk:resolveAVDHome Using $HOME/.android/avd/ at C:\Users\Pavitra\.android\avd +0ms
  native-run:android:utils:adb:getDevices Invoking adb with args: [ 'devices', '-l' ] +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing D:\AndroidSDK\platform-tools\package.xml +0ms
  native-run:android:utils:avd:getAVDINIs Discovered AVD ini files: [ 'C:\\Users\\Pavitra\\.android\\avd\\Pixel_4_API_30.ini' ] +0ms
  native-run:android:utils:sdk:findAllSDKPackages Walking D:\AndroidSDK to discover SDK packages +0ms
  native-run:android:utils:adb:parseAdbDevices Parsing adb devices from output lines: [
  native-run:android:utils:adb:parseAdbDevices   'List of devices attached',
  native-run:android:utils:adb:parseAdbDevices   'emulator-5554          device product:sdk_gphone_x86 model:sdk_gphone_x86 device:generic_x86_arm transport_id:1',
  native-run:android:utils:adb:parseAdbDevices   '',
  native-run:android:utils:adb:parseAdbDevices   ''
  native-run:android:utils:adb:parseAdbDevices ] +0ms
  native-run:android:utils:adb:getDeviceProperties Invoking adb with args: [ '-s', 'emulator-5554', 'shell', 'getprop' ]
 +0ms
  native-run:android:utils:adb:getDevices Found adb devices: [
  native-run:android:utils:adb:getDevices   {
  native-run:android:utils:adb:getDevices     serial: 'emulator-5554',
  native-run:android:utils:adb:getDevices     state: 'device',
  native-run:android:utils:adb:getDevices     type: 'emulator',
  native-run:android:utils:adb:getDevices     connection: null,
  native-run:android:utils:adb:getDevices     properties: {
  native-run:android:utils:adb:getDevices       product: 'sdk_gphone_x86',
  native-run:android:utils:adb:getDevices       model: 'sdk_gphone_x86',
  native-run:android:utils:adb:getDevices       device: 'generic_x86_arm',
  native-run:android:utils:adb:getDevices       transport_id: '1'
  native-run:android:utils:adb:getDevices     },
  native-run:android:utils:adb:getDevices     manufacturer: 'Google',
  native-run:android:utils:adb:getDevices     model: 'sdk_gphone_x86',
  native-run:android:utils:adb:getDevices     product: 'sdk_gphone_x86',
  native-run:android:utils:adb:getDevices     sdkVersion: '30'
  native-run:android:utils:adb:getDevices   }
  native-run:android:utils:adb:getDevices ] +100ms
  native-run:android:utils:sdk:getSDKPackage Parsing D:\AndroidSDK\emulator\package.xml +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing D:\AndroidSDK\tools\package.xml +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing D:\AndroidSDK\build-tools\29.0.3\package.xml +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing D:\AndroidSDK\build-tools\30.0.0\package.xml +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing D:\AndroidSDK\build-tools\30.0.2\package.xml +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing D:\AndroidSDK\build-tools\30.0.3\package.xml +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing D:\AndroidSDK\cmdline-tools\latest\package.xml +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing D:\AndroidSDK\patcher\v4\package.xml +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing D:\AndroidSDK\platforms\android-30\package.xml +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing D:\AndroidSDK\skiaparser\1\package.xml +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing D:\AndroidSDK\sources\android-30\package.xml +0ms
  native-run:android:utils:sdk:getSDKPackage Parsing D:\AndroidSDK\system-images\android-30\google_apis_playstore\x86\package.xml +0ms
  native-run:android:utils:sdk:api:getAPILevels Discovered installed API Levels: [
  native-run:android:utils:sdk:api:getAPILevels   {
  native-run:android:utils:sdk:api:getAPILevels     apiLevel: '30',
  native-run:android:utils:sdk:api:getAPILevels     packages: [
  native-run:android:utils:sdk:api:getAPILevels       'platforms;android-30',
  native-run:android:utils:sdk:api:getAPILevels       'system-images;android-30;google_apis_playstore;x86',
  native-run:android:utils:sdk:api:getAPILevels       'sources;android-30'
  native-run:android:utils:sdk:api:getAPILevels     ]
  native-run:android:utils:sdk:api:getAPILevels   }
  native-run:android:utils:sdk:api:getAPILevels ] +0ms
  native-run:android:utils:avd:getDefaultAVDSchematic Issue with API 30: Unsupported API level: 30 +0ms

Errors (!):

  ERR_UNSUITABLE_API_INSTALLATION: No suitable API installation found.

        More details for this error may be available online:

        https://github.com/ionic-team/native-run/wiki/Android-Errors

Connected Devices:

  No connected devices found

Virtual Devices:

  No virtual devices found
```

**Comment by phiberber** [comment]
Just saw you are using Windows. Might look at it later to see if it's prompting the same error.

**Comment by jcesarmobile** [comment]
Do you see the emulator listed in Android Studio?
I can't reproduce, can run on Android 30 and even Android S emulators without problems, so the problem is not that SDK 30 is not supported as pavi4210 suggests. But it's probably a problem on native-run or something misconfigured.

Can you try to run `npx native-run android --list` command?

**Comment by jkbz64** [comment]
Installing Android API 29 beside API 30 through android studio fixed the issue for me, can even launch API 30 devices through npx cap run android as well. The issue seems to occur only when the only installed API is 30.

**Comment by Harvtronix** [comment]
I have this same issue. For some additional information, I'd posted this issue over in the "discussions", unsure of if it was an issue or user error: https://github.com/ionic-team/capacitor/discussions/4230

**Comment by tmk1991** [comment]
> Installing Android API 29 beside API 30 through android studio fixed the issue for me, can even launch API 30 devices through npx cap run android as well. The issue seems to occur only when the only installed API is 30.

@jkbz64  - did you need to do anything after you installed an additional API? Still failing `npx cap run android` and `--list` yields no results.

If it's an ionic project should we run all cap commands via ionic cap XXX ? Not that it's helping but jw. 

@Harvtronix  any luck?

**Comment by jkbz64** [comment]
> > Installing Android API 29 beside API 30 through android studio fixed the issue for me, can even launch API 30 devices through npx cap run android as well. The issue seems to occur only when the only installed API is 30.
> 
> @jkbz64 - did you need to do anything after you installed an additional API? Still failing `npx cap run android` and `--list` yields no results.

Installing API 29 SDK was my last step, it worked for me after that. You can try setting environment variables like `CAPACITOR_ANDROID_STUDIO_PATH` and standard ones  like `JAVA_HOME` or `ANDROID_SDK_ROOT` since this is what I was trying before I found out about installing older SDK, other than that it was pretty much clean installation of android-studio from arch aur.

**Comment by jcesarmobile** [comment]
this was a bug in native-run, has been fixed in latest version (1.4.0)

since native-run is a dependency of @capacitor/cli, you can try to reinstall the CLI and it should pick the latest version, but make sure that was the case by checking the installed version in `package-lock.json`
If not updated, you can force update the dependency with `npm update native-run --depth 6 `

**Comment by tmk1991** [comment]
Updated native-run too 1.4.0. When I list targets with native-run it sees my emulators. Anything needed to sync capacitor or something? Still not seeing devices listed.
