### ISSUE TITLE
bug: Geolocation on Android always returning 'location unavailable'

### ISSUE THREAD

**Issue by jonathan-chin** [ionic-team/capacitor#4962]
### Capacitor Version

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.2.0
  @capacitor/core: 3.2.0
  @capacitor/android: 3.2.0
  @capacitor/ios: 3.2.0

Installed Dependencies:

  @capacitor/cli: 3.0.0
  @capacitor/core: 3.0.0
  @capacitor/android: 3.0.0
  @capacitor/ios: 3.1.2

[error] Xcode is not installed
[success] Android looking great! 👌
```

### Platform(s)

Android 10

### Current Behavior

When I try to call Geolocation.getCurrentPosition(), I always get an error: 'location unavailable'. I've tried this with no options and {enableHighAccuracy: true}.

I have the appropriate permissions set and the code works on PWA and iOS. The app has Location permission while in the foreground and Google Maps can get my location fine.

### Expected Behavior

Geolocation.getCurrentPosition() should provide the lat/lng of the current position.

### Code Reproduction

**edit:** basic repo set up here: https://github.com/jonathan-chin/capacitor-geocode-android-example
clicking on the `get currentposition` button will return `location unavailable` when running on a Google Pixel 3A on Android 10 through Android Studio.

it seems to have been an existing issue in the past #2854 but I am still experiencing it.

**Comment by Ionitron** [comment]
This issue may need more information before it can be addressed. In particular, it will need a reliable Code Reproduction that demonstrates the issue.

Please see the Contributing Guide for [how to create a Code Reproduction](https://github.com/ionic-team/capacitor/blob/HEAD/CONTRIBUTING.md#creating-a-code-reproduction).

Thanks!
Ionitron 💙

**Comment by exomc** [comment]
I've been using this plugin without any problems for weeks while developing my app. I've just updated all packages to the latest versions and now I am also experiencing this issue. Goes straight to error after giving the app permission. No error code or anything just 'location unavailable'

Ionic 6.17.0
Android Studio to Artic Fox | 2020.3.1 Patch 1

I'm getting the same thing on the emulator (with play store) as well as on my device. Web is fine.

Android build now generated the following warnings, not sure if they are relevant:

AGPBI: {"kind":"warning","text":"Using flatDirs should be avoided because it doesn't support any meta-data formats.\nCurrently detected usages:\n- repository flatDir used in: project ':app', project ':capacitor-cordova-android-plugins'","sources":[{}]}
AGPBI: {"kind":"warning","text":"Please remove usages of `jcenter()` Maven repository from your build scripts and migrate your build to other Maven repositories.\nThis repository is deprecated and it will be shut down in the future.\nSee http://developer.android.com/r/tools/jcenter-end-of-service for more information.\nCurrently detected usages in: root project 'android', project ':app', project ':capacitor-android', ...","sources":[{}]}

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
Use '--warning-mode all' to show the individual deprecation warnings.

**Comment by yang-shen-wen** [comment]
It's a Google Play Service bug.
I factory reset my phone, the problem is not happening.（Google Play Service v19.5.30）
Then update Google play Service to newest version (v21.30.16), the problem happened.

**Comment by jcesarmobile** [comment]
Looks like they removed the faulty version, on all my devices latest version is 21.26.21

**Comment by JDiApice** [comment]
I am still showing 21.30.16 on my Samsung Galaxy s21 Ultra with the last update 8/23/21.  There is not any pending updates for Google Play Services within the Google Play Store.   My Samsung Galaxy S9 is showing 21.24.18 which is the device that did not have any issues.

**Comment by jcesarmobile** [comment]
Yeah, they have removed that version from play store, but if it's already installed you have to manually uninstall it or wait for a newer version with the fix, it doesn't downgrade to the latest stable version automatically.

**Comment by jcesarmobile** [comment]
I'm closing the issue since it's a google services problem.
You can keep track of the sendLocation change (that should fix this issue) on https://github.com/ionic-team/capacitor-plugins/issues/571

**Comment by jcesarmobile** [comment]
looks like Google didn't remove 21.30.16 from play store as I just got it on my device

**Comment by AppskySpencer** [comment]
My Google Play Services version is 21.33.12 and I am still having the issue.

**Comment by jcesarmobile** [comment]
I've reported this issue on google issue tracker
https://issuetracker.google.com/issues/198176818

**Comment by luisdalopez56** [comment]
I have been testing on an android 7 and using native ionic Location accuracy I have been able to change the precision to the user and this way it works, but the problem comes with Android 11, there is no way to make it work

**Comment by Chamiyalt** [comment]
I have been tesing on GalaxyA32 (Android 11) the Geolocation plugin `await Geolocation.getCurrentPosition();` is retuned 
{"message":"location unavailable"} but it had been worked fine in 3 weeks ago. please give any solution asap. lot of users waiting for a fix.

**Comment by ignaciomarti** [comment]
Same issue... Temporarily solved by commenting out these lines in Geolocation.java

if (!availability.isLocationAvailable()) {
  call.error("location unavailable");
  clearLocationUpdates();
}

**Comment by jcesarmobile** [comment]
@capacitor/geolocation 1.1.0 is out with a fix

**Comment by KevinKelchen** [comment]
Awesome! 😀

Are there plans to release an update to Capacitor v2 with the same fix? I see someone has an open PR for it: https://github.com/ionic-team/capacitor/pull/4992 . Thought it might be worth asking since some of us have yet to upgrade to v3 and given the level of severity of the issue. 🙂

Thanks so much!

**Comment by FahmiChaar** [comment]
@KevinKelchen 
how you use patch-package ?
when i run `npx patch-package @capacitor/core` the output is `⁉️  There don't appear to be any changes.` and patches folder did not created

**Comment by KevinKelchen** [comment]
> @KevinKelchen
> how you use patch-package ?
> when i run `npx patch-package @capacitor/core` the output is `⁉️ There don't appear to be any changes.` and patches folder did not created

It’s not `@capacitor/core` that’s being patched but rather `@capacitor/android`. Try changing the package name. 🙂

**Comment by FahmiChaar** [comment]
> > @KevinKelchen
> > how you use patch-package ?
> > when i run `npx patch-package @capacitor/core` the output is `⁉️ There don't appear to be any changes.` and patches folder did not created
> 
> It’s not `@capacitor/core` that’s being patched but rather `@capacitor/android`. Try changing the package name. 🙂

thank you so much, it work now

**Comment by mtpultz** [comment]
@KevinKelchen it doesn't seem to fix the issue for us.  Are these the steps you used:

1. Access `@capacitor/android` and update `Geolocation.java` using this PRs changes (https://github.com/ionic-team/capacitor/pull/4992/files)
2. Run `npx patch-package @capacitor/android`
3. Update `package.json` with `"postinstall": "patch-package"`
4. `npm install patch-package` so dependency exists when `npm install` is run during Ionic AppFlow
5. Commit the patch file and changes to `package.json`

**Comment by jcesarmobile** [comment]
We have released @capacitor/android 2.5.0 with the fix, but please, update to capacitor 3 as soon as possible, it's not that hard and most fixes won't be backported to capacitor 2.

**Comment by 08-15at** [comment]
JFYI: looks like Google has updated Play-Services.
Version 21.33.13 seems to work with the old code....

**Comment by jcesarmobile** [comment]
not working for me with that version

**Comment by 08-15at** [comment]
strange...
seems as there could be some underlying Google code changes somewhere else: some customers reported, that it started working again after an automatic Android update on Sep. 3.
However it remained broken for others. 
So I asked some of those customers with a working device to send me their Play-Services version-info, it was still 21.30.16, but my app started working again on their devices  after an Android update on Sep. 3. without changes on my side. 
On my devices and the simulator I could see a Play-Service version  released on Sep. 3 in the Web PlayStore, but Play-Store let me  only install the Aug. 28 version where it would fail on my devices. 
I uploaded a workaround in place for my app Sept. 5, and I could update to your code, so no issue for me. 
However today I got 21.33.13 from the PlayStore and I tried my (unpatched) app version and  the previous failing Ionic Capacitor - Core Plugins Demo and it worked.

**Comment by krabien** [comment]
For our users, it appears to be intermittent. One user reports 80% fail 20% success on getting a GPS fix.
I don't know what Play Stores version they have.
Capacitor `2.5.0` fixes the issue on our testing environments, thanks so much Ionic team!

**Comment by NicolaiMogensen** [comment]
For our users, we have reports from 8th August, and 9th of september that location did not work for them. I can emulate a Pixel 2 API 28 that works fine in Android Studio. 

The user on 8th of August has Android 10 on a Galaxy A41 and the user on 9th of September has Android 11 on a Oneplus Pro 9  5G. 

The app we released worked on release, and has since seen reports of failure on the GPS. We use the Geolocation from capacitor/core and the manifest has the permissions included as the documentation says. Getting the play service versions has not been possible. Will try upgrading to 2.5.0 as @krabien said, and will see if that fixes it for us aswell

**Comment by Pendrokar** [comment]
**_capacitor/android 2.5_**
along with the dependency
**_capacitor/core 2.5_**

...does seem to fix the issue on an OnePlus 6. But on an emulated Pixel 3 API 30, while Geolocation.getCurrentPosition does get called, it never receives a result.

**Comment by JamesWaterhouse** [comment]
@jcesarmobile how's this coming along? Any word from Google on sorting it out? I'm reluctant to have to submit new builds with updated Capacitor plugins if its not a certainty that it'll work still.

**Comment by jcesarmobile** [comment]
Google said they reverted the changes last week and should work again, but play services updates takes time and not everybody gets them at the same time.

I would recommend updating as they don't recommend relying in `isLocationAvailable`, which the old versions used, but it's up to you.

**Comment by NicolaiMogensen** [comment]
Is there any official statement from google i can send to my users?

**Comment by jcesarmobile** [comment]
No official statement as far as I know, only a comment on the issue I reported
https://issuetracker.google.com/issues/198176818

**Comment by filifunk** [comment]
Hi I get this 'location unavailable' issue everytime I try to get my location on my phone (pixel 4a, google play services 22.33.16) for the first 5 minutes or so.  Then eventually I'm able to get a location.  I'm trying to make it so that I don't have to wait 5-10 minutes for a location.

I'm not really able to understand java but I'm getting "location unavailable" from this code block.  I know because I changed the error message so I knew it was coming from here:

```
	    
            fusedLocationClient = LocationServices.getFusedLocationProviderClient(context);

            LocationManager lm = (LocationManager) context.getSystemService(Context.LOCATION_SERVICE);
            if (this.isLocationServicesEnabled()) {
                boolean networkEnabled = false;

                try {
                    networkEnabled = lm.isProviderEnabled(LocationManager.NETWORK_PROVIDER);
                } catch (Exception ex) {}

                int lowPriority = networkEnabled ? Priority.PRIORITY_BALANCED_POWER_ACCURACY : Priority.PRIORITY_LOW_POWER;
                int priority = enableHighAccuracy ? Priority.PRIORITY_HIGH_ACCURACY : lowPriority;

                LocationRequest locationRequest = LocationRequest
                    .create()
                    .setMaxWaitTime(timeout)
                    .setInterval(10000)
                    .setFastestInterval(5000)
                    .setPriority(priority);

                locationCallback =
                    new LocationCallback() {
                        @Override
                        public void onLocationResult(LocationResult locationResult) {
                            Location lastLocation = locationResult.getLastLocation();
                            if (lastLocation == null) {
                                resultCallback.error("location unavailable test");
                            } else {
                                resultCallback.success(lastLocation);
                            }
                        }
                    };

                fusedLocationClient.requestLocationUpdates(locationRequest, locationCallback, null);
            } else {
                resultCallback.error("location disabled");
            }
        } else {
            resultCallback.error("Google Play Services not available");
        }
    }
```

I tried following the issuetracker link and using the code from the #105 post about the PRIORITY_HIGH_ACCURACY, and copied it in and got a lot of errors.  I also tried the solution of downgrading my gradle version but that gives me errors.  Any recommendations for what I should do?

**Comment by connectMyClub** [comment]
We're having the same issue. All was fine a week or so ago. I'm assuming it's a Google Play Service bug, as it has been previously, and we just have to wait for a fix.
