### ISSUE TITLE
Hot Reload XCode 15 iOS 17 not working on real device

### ISSUE THREAD

**Issue by epitomz** [ionic-team/capacitor#7019]
Hi everyone,

I'm developing an ionic app and I always use the `ionic capacitor run ios -l --external` command to have hot reload directly on my phone. Couple of days ago I started to get this error message after running it:

```
capacitor run ios --no-sync --target 00008110-001C610621E9801E
[capacitor] ✔ Running xcodebuild in 10.64s
[capacitor] ✖ Deploying App.app to 00008110-001C610621E9801E - failed!
[capacitor] [error] ERR_UNKNOWN: running on iOS 17 devices requires Xcode 15 and later
[capacitor]
[ERROR] An error occurred while running subprocess capacitor.

        capacitor run ios --no-sync --target 00008110-001C610621E9801E exited
        with exit code 1.
```

And if I try to use that same command with the simulator I get a stranger error : 

```
[capacitor]         ** BUILD FAILED **
[capacitor]
[capacitor]
[capacitor]         The following build commands failed:
[capacitor]         SwiftEmitModule normal x86_64 Emitting\ module\ for\ App (in target 'App' from project 'App')
[capacitor]         (1 failure)
[capacitor]
```

I dind't upgrade anything, neither on my phone nor on my mac. Except that, everything works fine when I use XCode to build the project : I can build the app with my real device or with the simulator using XCode but I can't with capacitor. 

I also tried to download the 17.0.1 runtime and add it with `xcrun simctl runtime add iOS_17.0.1_Simulator_Runtime.dmg`but it seems to be already here:

```
D: 26378338-76EE-4A06-8A22-62E291C3BEB5 iOS (17.0.1 - 21A342) (Unusable - Other Failure: Error Domain=SimDiskImageErrorDomain Code=5 "Duplicate of 8C7273B9-FA0F-4A6C-96EC-753C382B832F" UserInfo={NSLocalizedDescription=Duplicate of 8C7273B9-FA0F-4A6C-96EC-753C382B832F, unusableErrorDetail=})
```

- Mac os Sonoma 14.0
- Iphone 13, 17.0.3
- XCode 15.0.1
- Simulator 15.0.1
- @capacitor/ios 4.5.1
- Ionic CLI 7.1.1
- Node 18.16.1

Would you have any ideas how I can repair that?

Thanks in advance

**Comment by jcesarmobile** [comment]
It was a problem on native-run and was fixed and released yesterday, uninstall and reinstall latest `@capacitor/cli` so it install latest version of native-run, or install native-run in your project and make sure you have 1.7.4 installed.

**Comment by behicsakar** [comment]
I upgraded capacitor-cli, and cococapods but it didnt work for me. 

I solved it with 

0- Before i start this procedure, i upgraded version of `cocoapods` from `1.13.x` to `1.14.2` by using the following command, homebrew `brew upgrade cocoapods`

1- Delete `DerivedData` folder and `capacitor-cordova-ios-plugins` if exists
<img width="266" alt="Screenshot 2023-10-29 at 01 10 27" src="https://github.com/ionic-team/capacitor/assets/3280475/9d8f56a1-2d4c-4386-92c0-ce867b6d48ec">

2- Go to `ios/App` and delete `Pods` folder
<img width="276" alt="Screenshot 2023-10-29 at 01 11 56" src="https://github.com/ionic-team/capacitor/assets/3280475/64908de1-a1fb-430f-a17b-3990d8d69d5c">

3- run `pod install` inside of `ios/App`

4- go to root folder which your project is located and run `ionic cap sync`

5- Better first test directly run this project in a simulator `ionic cap run ios` and choose a device.

6- If everyyhing works fine then try to run `ionic capacitor run ios -l --external`

**Comment by mwyld** [comment]
I tried @behics solution which worked on my iPhone X but strangely still get the same error on my iPhone 14

**Comment by KirstenStake** [comment]
had the same issue for ages. updated my "@capacitor/cli" and was still happening. then re-read the comment above and i had to **uninstall** @capacitor/cli first and then re-install. that then resolved it.
