### ISSUE TITLE
[Bug]: xml resources not merged into AndroidManifest

### ISSUE THREAD

**Issue by soundwave12345** [ionic-team/capacitor#8273]
### Capacitor Version

capacitor 7.0.2

### Other API Details

```Shell

```

### Platforms Affected

- [ ] iOS
- [x] Android
- [ ] Web

### Current Behavior

I'm crafting a plugin to use android auto with my app.
To be able to use my app on AA it needed to have this in androidmanifest.xml:
```
               <meta-data 
            android:name="com.google.android.gms.car.application"
            android:resource="@xml/automotive_app_desc" />
```
   
then the linked file in /android/src/main/res/xml/automotive_app_desc.xml

```
<?xml version="1.0" encoding="utf-8"?>
<automotiveApp>
    <uses name="media"/>
</automotiveApp>
```

After the merge in androidmanifest i have:

```
               <meta-data 
            android:name="com.google.android.gms.car.application"
            android:resource="automotive_app_desc" />
```
and no automotive_app_desc.xml in any location of the project.

To be able to build for android auto I have to manually add after npx cap sync the file in:
/android/src/main/automotive_app_desc.xml

It would be nice to have it auto merged.

### Expected Behavior

Merged automatically. in AndroidManifest.xml and related files

### Project Reproduction

https://github.com/soundwave12345/capacitor-android-auto/

**Comment by Suryansh0910** [comment]
@soundwave12345 I am working on this!
Will raise a PR soon!

**Comment by White-D-coder** [comment]
@soundwave12345 Hey, I believe I’ve fixed the issue. Could you review it when you get a chance? I’ve already opened a PR.

**Comment by soundwave12345** [comment]
@White-D-coder just tried with this package.json:

```
  "dependencies": {
    "@capacitor-plus/android": "8.0.0-beta.0",
    "@capacitor-plus/core": "8.0.0-beta.0",
    "lucide-react": "^0.344.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@capacitor-plus/cli": "8.0.0-beta.0",
```
in the main app, not in the plugin.
xml still not existent.

**Comment by soundwave12345** [comment]
@White-D-coder sorry tough this PR was already merged.
