### ISSUE TITLE
[Bug]: System Bar safe-area-inset-x ignores Keyboard state

### ISSUE THREAD

**Issue by schwebke** [ionic-team/capacitor#8287]
### Capacitor Version

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 8.0.0
  @capacitor/core: 8.0.0
  @capacitor/android: 8.0.0
  @capacitor/ios: 8.0.0

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 8.0.0
  @capacitor/core: 8.0.0
  @capacitor/android: 8.0.0

[success] Android looking great! 👌

### Other API Details

```Shell
npm --version: 11.6.2
node --version: v24.11.1
```

### Platforms Affected

- [ ] iOS
- [x] Android
- [ ] Web

### Current Behavior

With `plugin.SystemBars.insetsHandling` = `css` and no keyboard my app works fine using:
```
body {
    box-sizing: border-box;
    height: 100dvh;
    width: 100dvw;
    padding-top: var(--safe-area-inset-top, env(safe-area-inset-top, 0px));
    padding-bottom: var(--safe-area-inset-bottom, env(safe-area-inset-bottom, 0px));
    padding-left: var(--safe-area-inset-left, env(safe-area-inset-left, 0px));
    padding-right: var(--safe-area-inset-right, env(safe-area-inset-right, 0px));
    display: flex;
}
```

With the keyboard displayed, the bottom inset remains, creating superfluous spacing between the upper border of the on screen keyboard and the webview content.

As a workaround I added as css style ...
```
body.no-bottom-inset {
    --safe-area-inset-bottom: 0px;
}
```
... and these handlers in my code:
```    
    Keyboard.addListener('keyboardWillShow', info => {
        console.log('keyboard did show with height:', info.keyboardHeight);
        document.body.classList.add('no-bottom-inset');
    });

    Keyboard.addListener('keyboardWillHide', () => {
        console.log('keyboard did hide');
        document.body.classList.remove('no-bottom-inset');
    });
```

### Expected Behavior

I feel making `safe-area-inset-x` variables keyboard aware would be more natural.

### Project Reproduction

https://github.com/schwebke/capacitor-system-bar-keyboard-interaction

### Additional Information

Screenshots showing the issue and the effect of the workaround:
https://github.com/schwebke/capacitor-system-bar-keyboard-interaction/tree/main/screenshots

**Comment by theproducer** [comment]
This has been fixed in:
https://github.com/ionic-team/capacitor/pull/8280

We will be doing a point release soon with these and other fixes.

**Comment by croraf** [comment]
In capacitor config I have `insetsHandling` not set (default, that is "css").

Without the keyboard open it works fine.  

But it is not clear how to handle bottom inset when keyboard is open. On the contrary of the original poster I used `calc(env(safe-area-inset-bottom) + env(keyboard-inset-height));`, which ofc adds the two of them. Would it be most natural in the case the keyboard is open that Capacitor sets `env(safe-area-inset-bottom) = 0` ?

EDIT: Ok, I see this is actually what was done in the #8280

**Comment by croraf** [comment]
I've upgraded to 8.0.1 and ran `npx cap sync`.

```
"dependencies": {
    "@capacitor/android": "^8.0.1",
    "@capacitor/app": "^8.0.0",
    "@capacitor/core": "8.0.1",
    "@capacitor/splash-screen": "8.0.0"
  },
  "devDependencies": {
    "@capacitor/cli": "8.0.1",
    "prettier": "^3.7.4",
    "typescript": "^5.9.3"
  },
```


But I still have this bug that the safe-area-inset-bottom is not removed when keyboard is open.

```css
#root {
  position: fixed;
  top: env(safe-area-inset-top);
  bottom: calc(env(safe-area-inset-bottom) + env(keyboard-inset-height));
  left: env(safe-area-inset-left, 0px);
  right: env(safe-area-inset-right, 0px);
  overflow: hidden;
}
```

WebView implementation 144.0.7559.59.

<img width="306" height="686" alt="Image" src="https://github.com/user-attachments/assets/0ad9be42-13af-4d42-94fb-9c6ff9925ee0" />

**Comment by theproducer** [comment]
@croraf Do you have a project we can take a look at to see what's going on?

**Comment by croraf** [comment]
@theproducer https://github.com/croraf/capacitor-8.0.1-e2e-bug  here is the minimal example.

(Btw when setting up the project initially, on `npx cap sync` it throws an error and I have to create the assets folder manually)

**Comment by croraf** [comment]
@theproducer I've pushed new version with a simplified html and css.

**Comment by theproducer** [comment]
@croraf I changed your `#root` css to this (from: https://capacitorjs.com/docs/apis/system-bars#android-note):
```
#root {
  /* position: absolute; */
  position: fixed;
  top: var(--safe-area-inset-top, env(safe-area-inset-top, 0px));  
  bottom: var(--safe-area-inset-bottom, env(safe-area-inset-bottom, 0px));
  left: var(--safe-area-inset-left, env(safe-area-inset-left, 0px));
  right: var(--safe-area-inset-right, env(safe-area-inset-right, 0px));
  background: lightblue;
}
```
Everything seems to be working as expected.  Can you try on your end?

**Comment by croraf** [comment]
@theproducer Yes your example works correctly.

But it is confusing. 

1. If `--safe-area-inset-*` variables are defined by the capacitor framework why the `env` in the fallback?

2.  `--safe-area-inset-bottom` is set to `0` when the keyboard is opened? How come the div is then shrinked when the keyboard is opened?

3. Android System WebView is automatically updated, so now I have version 145. This means env variables should always be correctly injected on all devices and we don't need to handle versions <= 139.

4. The issue still remains as my original example should work?

**Comment by croraf** [comment]
Reminder about my question. 

So my conclusion is basically that the injected variables (the ones with --) work ok, but the env variables seem not to be good (as per my previous example).
